#!/usr/bin/env bash
# Bash (init) script to manage manage_my_process.

# Check if argument is provided
if [ $# -eq 0 ]; then
    echo "Usage: $0 {start|stop|restart}"
    exit 1
fi

# Execute the specified action
case "$1" in
    start)
        ./manage_my_process start
        ;;
    stop)
        ./manage_my_process stop
        ;;
    restart)
        ./manage_my_process restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac

exit 0
